### Best Practices for NLP Projects
1. Focus on preprocessing and data cleaning
2. Train Test Split
3. BOW and TFIDF (Sentences ---> Vectors) {Preventing Data Leakage - Data leakage is when the model is trained on the test data}
4. Model Training
5. Model Evaluation

In [1]:
import pandas as pd
df = pd.read_csv("/Users/saumyagupta/Documents/AI Engineer Roadmap with Projects/Natural Language Processing/Datasets/SMSSpamCollection.txt", sep='\t', names=['label', 'message'])
df

label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [2]:
import re 
import nltk
nltk.download('stopwords')

from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

stemmer = PorterStemmer()

corpus = []

for i in range(len(df)):
    review = re.sub('[^a-zA-Z]', ' ', df['message'][i])
    review = review.lower()
    review = review.split()
    review = [stemmer.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/saumyagupta/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [3]:
corpus

['go jurong point crazi avail bugi n great world la e buffet cine got amor wat',
 'ok lar joke wif u oni',
 'free entri wkli comp win fa cup final tkt st may text fa receiv entri question std txt rate c appli',
 'u dun say earli hor u c alreadi say',
 'nah think goe usf live around though',
 'freemsg hey darl week word back like fun still tb ok xxx std chg send rcv',
 'even brother like speak treat like aid patent',
 'per request mell mell oru minnaminungint nurungu vettam set callertun caller press copi friend callertun',
 'winner valu network custom select receivea prize reward claim call claim code kl valid hour',
 'mobil month u r entitl updat latest colour mobil camera free call mobil updat co free',
 'gonna home soon want talk stuff anymor tonight k cri enough today',
 'six chanc win cash pound txt csh send cost p day day tsandc appli repli hl info',
 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw',
 'search right word thank breather

In [36]:
# Create Bag of Words model

# Dependent Variable
y = pd.get_dummies(df['label'])
#Taking only ham values as it is a binary classification problem
y = y.iloc[:,0].values

# Train Test Split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(corpus, y, test_size=0.2, random_state=0)


from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=1000,ngram_range=(1,2))
X_train = cv.fit_transform(X_train).toarray()
X_test = cv.transform(X_test).toarray()

import numpy as np
np.set_printoptions(edgeitems=30, linewidth=100000, formatter={'float_kind':lambda x: "%.3f" % x})
X_train

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0

In [10]:
X.shape

cv.vocabulary_

{'go': 327,
 'point': 654,
 'crazi': 174,
 'avail': 44,
 'great': 345,
 'world': 975,
 'got': 342,
 'wat': 937,
 'ok': 598,
 'lar': 451,
 'joke': 432,
 'wif': 959,
 'free': 297,
 'entri': 248,
 'wkli': 970,
 'comp': 153,
 'win': 962,
 'cup': 178,
 'final': 282,
 'st': 800,
 'may': 513,
 'text': 841,
 'receiv': 692,
 'question': 680,
 'std': 807,
 'txt': 887,
 'rate': 684,
 'appli': 33,
 'free entri': 299,
 'dun': 230,
 'say': 735,
 'earli': 233,
 'alreadi': 19,
 'think': 849,
 'goe': 331,
 'usf': 914,
 'live': 479,
 'around': 36,
 'though': 852,
 'freemsg': 301,
 'hey': 382,
 'week': 946,
 'word': 973,
 'back': 52,
 'like': 471,
 'fun': 311,
 'still': 808,
 'xxx': 987,
 'send': 750,
 'even': 252,
 'brother': 80,
 'speak': 797,
 'treat': 876,
 'per': 629,
 'request': 708,
 'set': 755,
 'callertun': 102,
 'caller': 100,
 'press': 664,
 'copi': 166,
 'friend': 305,
 'winner': 964,
 'valu': 919,
 'network': 567,
 'custom': 181,
 'select': 746,
 'prize': 670,
 'reward': 712,
 'claim': 132,


In [37]:
y

array([ True,  True, False,  True,  True, False,  True,  True, False, False,  True, False, False,  True,  True, False,  True,  True,  True, False,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True, ...,  True,  True,  True,  True,  True, False,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True,  True, False, False,  True,  True,  True,  True])

In [38]:
# Training model using Naive Bayes Classifier
from sklearn.naive_bayes import MultinomialNB
spam_detect_model = MultinomialNB().fit(X_train, y_train)

y_pred=spam_detect_model.predict(X_test)

In [39]:
from sklearn.metrics import accuracy_score, classification_report
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: ", accuracy)
print("Classification Report:\n", classification_report(y_test, y_pred))

Accuracy:  0.9820627802690582
Classification Report:
               precision    recall  f1-score   support

       False       0.94      0.93      0.94       160
        True       0.99      0.99      0.99       955

    accuracy                           0.98      1115
   macro avg       0.97      0.96      0.96      1115
weighted avg       0.98      0.98      0.98      1115



In [40]:
accuracy

0.9820627802690582

In [23]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[149,  11],
       [  8, 947]])

In [41]:
# Creating TFIDF Model
from sklearn.feature_extraction.text import TfidfVectorizer

X_train, X_test, y_train, y_test = train_test_split(corpus, y, test_size=0.2, random_state=0)

tfidf = TfidfVectorizer(max_features=2500,ngram_range=(2,3))
X_train = tfidf.fit_transform(X_train).toarray()
X_test = tfidf.transform(X_test).toarray()


spam_detect_model = MultinomialNB().fit(X_train, y_train)

y_pred=spam_detect_model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: ", accuracy)
print("Classification Report:\n", classification_report(y_test, y_pred))
accuracy


Accuracy:  0.9488789237668162
Classification Report:
               precision    recall  f1-score   support

       False       1.00      0.64      0.78       160
        True       0.94      1.00      0.97       955

    accuracy                           0.95      1115
   macro avg       0.97      0.82      0.88      1115
weighted avg       0.95      0.95      0.94      1115



0.9488789237668162

In [42]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm  

array([[103,  57],
       [  0, 955]])